// Command verify runs proofs built by the Rust implementation through katie's
// verifiers — the Rust → Go direction of docs/interop.md Tier 1.
//
// Every other program in interop/ goes the other way: katie produces a value and
// the Rust side recomputes it. That cannot catch an implementation that is
// self-consistently wrong, and it cannot catch over-acceptance — a verifier that
// accepts a proof the peer would reject. This one can, because katie is the one
// deciding.
//
// It links github.com/Bren2010/katie, which is AGPL-3.0; see ../../README.md and
// ../../../docs/licensing.md for why this module carries that licence.
//
// Usage:
//
//	go run ./cmd/verify -in ../vectors/from-kt.json
package main

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"

	"github.com/Bren2010/katie/crypto/suites"
	"github.com/Bren2010/katie/crypto/vrf/edwards25519"
	"github.com/Bren2010/katie/tree/log"
	"github.com/Bren2010/katie/tree/prefix"
	"github.com/Bren2010/katie/tree/transparency/algorithms"
	"github.com/Bren2010/katie/tree/transparency/structs"
)

// file mirrors what kt-interop-emit writes.
type file struct {
	Primitive string         `json:"primitive"`
	Draft     string         `json:"draft"`
	Generator generator      `json:"generator"`
	Notes     string         `json:"notes"`
	Cases     []caseEnvelope `json:"cases"`
}

type generator struct {
	Impl    string `json:"impl"`
	Version string `json:"version"`
}

// caseEnvelope carries every field either kind of case can use; `kind` selects
// which are meaningful. Keeping one struct avoids a second decode pass.
type caseEnvelope struct {
	Kind   string `json:"kind"`
	Name   string `json:"name"`
	Expect string `json:"expect"`

	// log-tree
	Size         uint64   `json:"size"`
	Entries      []uint64 `json:"entries"`
	Values       []string `json:"values"`
	RetainedSize *uint64  `json:"retained_size"`
	Retained     []string `json:"retained"`
	Elements     []string `json:"elements"`

	// prefix-tree
	Searches []search `json:"searches"`
	Proof    string   `json:"proof"`

	// prefix-mutation
	Added   []leaf `json:"added"`
	Removed []leaf `json:"removed"`
	Before  string `json:"before"`
	After   string `json:"after"`

	// combined-search — `size` is shared with log-tree above.
	Operation  string       `json:"operation"`
	Greatest   uint32       `json:"greatest"`
	Timestamps []uint64     `json:"timestamps"`
	Versions   []versionKey `json:"versions"`
	Map        []mapEntry   `json:"map"`

	// auditor-update
	Encoding string `json:"encoding"`

	Root string `json:"root"`
}

type mapEntry struct {
	Position uint64 `json:"position"`
	Version  uint32 `json:"version"`
}

type versionKey struct {
	Version    uint32  `json:"version"`
	VrfOutput  string  `json:"vrf_output"`
	Commitment *string `json:"commitment"`
}

type leaf struct {
	VrfOutput  string `json:"vrf_output"`
	Commitment string `json:"commitment"`
}

type search struct {
	VrfOutput  string  `json:"vrf_output"`
	Commitment *string `json:"commitment"`
}

const (
	accept = "accept"
	reject = "reject"
)

func main() {
	in := flag.String("in", "../vectors/from-kt.json", "file of kt-generated proofs to verify")
	verbose := flag.Bool("v", false, "print a line per case")
	flag.Parse()

	raw, err := os.ReadFile(*in)
	if err != nil {
		fatalf("reading %s: %v", *in, err)
	}
	var f file
	if err := json.Unmarshal(raw, &f); err != nil {
		fatalf("parsing %s: %v", *in, err)
	}
	if f.Generator.Impl != "kt" {
		fatalf("%s was not generated by kt (impl = %q)", *in, f.Generator.Impl)
	}
	if len(f.Cases) == 0 {
		fatalf("%s has no cases", *in)
	}

	cs := suites.KTSha256Ed25519{}
	var accepted, rejected, failures int

	for _, c := range f.Cases {
		if c.Expect != accept && c.Expect != reject {
			fatalf("case %q: expect must be %q or %q, got %q", c.Name, accept, reject, c.Expect)
		}

		var err error
		switch c.Kind {
		case "log-tree":
			err = checkLogTree(cs, c)
		case "prefix-tree":
			err = checkPrefixTree(cs, c)
		case "prefix-mutation":
			err = checkPrefixMutation(cs, c)
		case "combined-search":
			err = checkCombinedSearch(cs, c)
		case "auditor-update":
			err = checkAuditorUpdate(cs, c)
		default:
			fatalf("case %q: unknown kind %q", c.Name, c.Kind)
		}

		got := accept
		if err != nil {
			got = reject
		}
		if got == accept {
			accepted++
		} else {
			rejected++
		}

		if got != c.Expect {
			failures++
			if c.Expect == accept {
				fmt.Printf("FAIL %s: katie rejected a proof it should accept: %v\n", c.Name, err)
			} else {
				fmt.Printf("FAIL %s: katie accepted a proof it should reject\n", c.Name)
			}
		} else if *verbose {
			fmt.Printf("ok   %s (%s)\n", c.Name, got)
		}
	}

	fmt.Printf(
		"%d cases from %s: %d accepted, %d rejected, %d disagreements\n",
		len(f.Cases), f.Generator.Impl, accepted, rejected, failures,
	)
	if failures > 0 {
		os.Exit(1)
	}
}

// checkPrefixMutation replays a §15.2 update through katie's own EvaluateBeforeAfter and
// requires it to land on both roots the Rust side computed.
//
// Only the shapes where the two implementations are known to agree are sent: katie does
// not recognize §11.9's all-zero copath element as an empty subtree, and it refuses a
// replacement outright, so those two are excluded by the emitter rather than expected to
// fail here. Both are recorded in ../../vectors/prefix-mutation.json and written up in
// ../../../docs/interop.md — this direction is for checking agreement, not for restating
// a divergence the other direction already pins.
func checkPrefixMutation(cs suites.CipherSuite, c caseEnvelope) error {
	added, err := unhexLeaves(c.Added)
	if err != nil {
		return fmt.Errorf("added: %w", err)
	}
	removed, err := unhexLeaves(c.Removed)
	if err != nil {
		return fmt.Errorf("removed: %w", err)
	}
	wantBefore, err := hex.DecodeString(c.Before)
	if err != nil {
		return fmt.Errorf("before: %w", err)
	}
	wantAfter, err := hex.DecodeString(c.After)
	if err != nil {
		return fmt.Errorf("after: %w", err)
	}
	raw, err := hex.DecodeString(c.Proof)
	if err != nil {
		return fmt.Errorf("proof: %w", err)
	}
	buf := bytes.NewBuffer(raw)
	proof, err := prefix.NewPrefixProof(cs, buf)
	if err != nil {
		return fmt.Errorf("parsing the proof: %w", err)
	} else if buf.Len() != 0 {
		return fmt.Errorf("%d bytes left after the proof", buf.Len())
	}

	before, after, err := prefix.EvaluateBeforeAfter(cs, added, removed, proof)
	if err != nil {
		return fmt.Errorf("evaluating: %w", err)
	}
	if !bytes.Equal(before, wantBefore) {
		return errors.New("the root before the update does not match")
	}
	if !bytes.Equal(after, wantAfter) {
		return errors.New("the root after the update does not match")
	}
	return nil
}

// checkCombinedSearch runs a CombinedTreeProof built by the Rust side through katie's own §6.3.
//
// This is the direction that catches over-acceptance. Everything else about §6–§8 runs the other
// way — katie serves a response and the Rust side replays it — which cannot reveal a proof the
// Rust side would accept and katie would not. The one real bug in this project's history was found
// exactly here: §12.1's balanced-subtree rule, which self-consistent proofs satisfied and katie
// rejected.
//
// No signature is involved. katie's algorithm layer verifies a proof through a ProofHandle without
// a tree head, so the Rust side does not have to become a log to be checked as a verifier.
// `handle.Finish()` is katie's own version of §12.3's exact-count rule, so a proof carrying one
// element too many or too few fails there rather than passing quietly.
func checkCombinedSearch(cs suites.CipherSuite, c caseEnvelope) error {
	raw, err := hex.DecodeString(c.Proof)
	if err != nil {
		return fmt.Errorf("proof: %w", err)
	}
	buf := bytes.NewBuffer(raw)
	proof, err := structs.NewCombinedTreeProof(cs, buf)
	if err != nil {
		return fmt.Errorf("parsing the proof: %w", err)
	} else if buf.Len() != 0 {
		return fmt.Errorf("%d bytes left after the proof", buf.Len())
	}

	handle := algorithms.NewReceivedProofHandle(cs, *proof)
	for _, v := range c.Versions {
		vrfOutput, err := hex.DecodeString(v.VrfOutput)
		if err != nil {
			return fmt.Errorf("version %d vrf_output: %w", v.Version, err)
		}
		var commitment []byte
		if v.Commitment != nil {
			commitment, err = hex.DecodeString(*v.Commitment)
			if err != nil {
				return fmt.Errorf("version %d commitment: %w", v.Version, err)
			}
		}
		if err := handle.AddVersion(v.Version, vrfOutput, commitment); err != nil {
			return fmt.Errorf("version %d: %w", v.Version, err)
		}
	}

	config, err := searchConfig(cs)
	if err != nil {
		return err
	}
	provider := algorithms.NewDataProvider(cs, handle)
	// §12.3.1 first, exactly as a client does: the view update consumes the frontier's timestamps
	// before the search asks for anything.
	if err := algorithms.UpdateView(config, c.Size, nil, provider); err != nil {
		return fmt.Errorf("updating the view: %w", err)
	}
	// Each operation is a different reader of the same structure, which is the point: the proof's
	// elements only mean anything in the order the algorithm being run asks for them.
	switch c.Operation {
	case "greatest-version":
		if _, err := algorithms.GreatestVersionSearch(config, c.Greatest, c.Size, provider); err != nil {
			return fmt.Errorf("greatest-version search: %w", err)
		}
	case "fixed-version":
		if _, err := algorithms.FixedVersionSearch(config, c.Greatest, c.Size, provider); err != nil {
			return fmt.Errorf("fixed-version search: %w", err)
		}
	case "contact-monitor":
		monitor, err := algorithms.NewMonitor(config, c.Size, provider)
		if err != nil {
			return fmt.Errorf("creating the monitor: %w", err)
		}
		ptrs := make(map[uint64]uint32, len(c.Map))
		for _, entry := range c.Map {
			ptrs[entry.Position] = entry.Version
		}
		monitor.Contact = &algorithms.ContactState{Ptrs: ptrs}
		if err := monitor.ContactMonitor(); err != nil {
			return fmt.Errorf("contact monitor: %w", err)
		}
	default:
		return fmt.Errorf("unknown operation %q", c.Operation)
	}
	// The provider's Finish is the whole closing sequence a client performs: it in-fills the prefix
	// roots for entries that have a timestamp and no proof, hashes every inspected leaf, evaluates
	// the log tree inclusion proof against them, and refuses if anything is left unconsumed. So it
	// checks more than §12.3's exact-count rule — it also checks that the log tree proof this side
	// built actually roots the leaves it names.
	if _, err := provider.Finish(c.Size, nil, nil); err != nil {
		return fmt.Errorf("finishing: %w", err)
	}
	return nil
}

// searchConfig is the public configuration these proofs are checked against.
//
// The monitoring window is the field that matters for the proof: the Rust side builds its logs with
// entries a millisecond apart, so a week-long window leaves only the root distinguished and §6.3
// starts there.
//
// The clock bounds are deliberately enormous. §4.2 has a verifier check the rightmost timestamp
// against its own clock, which is a deployment policy rather than a property of a proof — and these
// fixtures carry fixed timestamps so that from-kt.json regenerates to identical bytes. Making the
// fixture track the wall clock would trade a reproducible artifact for a check that belongs
// elsewhere; tree-head.json already pins the clock bounds themselves.
func searchConfig(cs suites.CipherSuite) (*structs.PublicConfig, error) {
	logKey, err := cs.ParseSigningPrivateKey(bytes.Repeat([]byte{0x71}, 32))
	if err != nil {
		return nil, fmt.Errorf("parsing the log signing key: %w", err)
	}
	vrfKey, err := edwards25519.NewPrivateKey(bytes.Repeat([]byte{0x74}, 32))
	if err != nil {
		return nil, fmt.Errorf("parsing the VRF key: %w", err)
	}
	return &structs.PublicConfig{
		SignatureKey: logKey.Public(),
		VrfKey:       vrfKey.PublicKey(),
		Config: structs.Config{
			Suite:                      cs,
			Mode:                       structs.ContactMonitoring,
			MaxAhead:                   1 << 62,
			MaxBehind:                  1 << 62,
			ReasonableMonitoringWindow: 604800000,
		},
	}, nil
}

// checkAuditorUpdate parses an `AuditorUpdate` the Rust side encoded and re-marshals it,
// which is the only direction that tests katie's *decoder* against our encoder. The
// element-counted `PrefixLeaf added<0..2^16-1>` vectors are the reason to bother: a
// decoder reading that bound as a byte count would still consume a plausible-looking
// message off these bytes, just a different one.
func checkAuditorUpdate(cs suites.CipherSuite, c caseEnvelope) error {
	raw, err := hex.DecodeString(c.Encoding)
	if err != nil {
		return fmt.Errorf("encoding: %w", err)
	}
	buf := bytes.NewBuffer(raw)
	update, err := structs.NewAuditorUpdate(cs, buf)
	if err != nil {
		return fmt.Errorf("parsing: %w", err)
	} else if buf.Len() != 0 {
		return fmt.Errorf("%d bytes left after the update", buf.Len())
	}

	var out bytes.Buffer
	if err := update.Marshal(&out); err != nil {
		return fmt.Errorf("re-marshalling: %w", err)
	}
	if !bytes.Equal(out.Bytes(), raw) {
		return errors.New("re-marshalling produced different bytes")
	}
	return nil
}

func unhexLeaves(leaves []leaf) ([]prefix.Entry, error) {
	out := make([]prefix.Entry, 0, len(leaves))
	for i, l := range leaves {
		vrfOutput, err := hex.DecodeString(l.VrfOutput)
		if err != nil {
			return nil, fmt.Errorf("leaf %d vrf_output: %w", i, err)
		}
		commitment, err := hex.DecodeString(l.Commitment)
		if err != nil {
			return nil, fmt.Errorf("leaf %d commitment: %w", i, err)
		}
		out = append(out, prefix.Entry{VrfOutput: vrfOutput, Commitment: commitment})
	}
	return out, nil
}

// checkLogTree runs one batch proof through katie's log verifier (draft §12.1).
//
// katie's Evaluate returns the full subtree heads it computed rather than a root,
// so the root comes from log.Root. A proof is "accepted" only if the verifier
// raises nothing *and* lands on the root the Rust side claimed: a tampered element
// usually produces a different root rather than an error, and treating that as
// acceptance would make every negative case pass for the wrong reason.
func checkLogTree(cs suites.CipherSuite, c caseEnvelope) error {
	values, err := unhexAll(c.Values)
	if err != nil {
		return fmt.Errorf("values: %w", err)
	}
	elements, err := unhexAll(c.Elements)
	if err != nil {
		return fmt.Errorf("elements: %w", err)
	}
	wantRoot, err := hex.DecodeString(c.Root)
	if err != nil {
		return fmt.Errorf("root: %w", err)
	}

	v := log.NewVerifier(cs)
	if c.RetainedSize != nil {
		retained, err := unhexAll(c.Retained)
		if err != nil {
			return fmt.Errorf("retained: %w", err)
		}
		if err := v.Retain(*c.RetainedSize, retained); err != nil {
			return fmt.Errorf("retaining: %w", err)
		}
	}

	fullSubtrees, _, err := v.Evaluate(c.Entries, c.Size, nil, values, elements)
	if err != nil {
		return fmt.Errorf("evaluating: %w", err)
	}
	root, err := log.Root(cs, c.Size, fullSubtrees)
	if err != nil {
		return fmt.Errorf("computing the root: %w", err)
	}
	if !bytes.Equal(root, wantRoot) {
		return errors.New("proof evaluates to a different root")
	}
	return nil
}

// checkPrefixTree parses the Rust side's wire-encoded PrefixProof and verifies it
// (draft §12.2). Parsing with katie's own NewPrefixProof means the encoding is
// under test too, not just the hashing.
func checkPrefixTree(cs suites.CipherSuite, c caseEnvelope) error {
	proofBytes, err := hex.DecodeString(c.Proof)
	if err != nil {
		return fmt.Errorf("proof: %w", err)
	}
	buf := bytes.NewBuffer(proofBytes)
	proof, err := prefix.NewPrefixProof(cs, buf)
	if err != nil {
		return fmt.Errorf("parsing the proof: %w", err)
	}
	if buf.Len() != 0 {
		return fmt.Errorf("%d trailing bytes after the proof", buf.Len())
	}

	entries := make([]prefix.Entry, 0, len(c.Searches))
	for i, s := range c.Searches {
		vrfOutput, err := hex.DecodeString(s.VrfOutput)
		if err != nil {
			return fmt.Errorf("search %d: vrf_output: %w", i, err)
		}
		entry := prefix.Entry{VrfOutput: vrfOutput}
		if s.Commitment != nil {
			commitment, err := hex.DecodeString(*s.Commitment)
			if err != nil {
				return fmt.Errorf("search %d: commitment: %w", i, err)
			}
			entry.Commitment = commitment
		}
		entries = append(entries, entry)
	}

	root, err := hex.DecodeString(c.Root)
	if err != nil {
		return fmt.Errorf("root: %w", err)
	}
	return prefix.Verify(cs, entries, proof, root)
}

func unhexAll(values []string) ([][]byte, error) {
	out := make([][]byte, 0, len(values))
	for i, value := range values {
		decoded, err := hex.DecodeString(value)
		if err != nil {
			return nil, fmt.Errorf("element %d: %w", i, err)
		}
		out = append(out, decoded)
	}
	return out, nil
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "verify: "+format+"\n", args...)
	os.Exit(1)
}
