//! Rendering a [`Report`] as a single self-contained page.
//!
//! No JavaScript, no external requests, no build step: the page is one file that
//! can be read in a terminal browser or archived as evidence. Every case is
//! rendered, expanded on demand; nothing is truncated, because a report that
//! hides values is asking to be believed rather than checked.

use std::fmt::Write as _;

use crate::report::{Area, Case, Check, Coverage, Report, Suite, Verdict};

/// Where the vectors and the code live, for the page's links.
const REPO: &str = "https://github.com/OR13/kt";
const DRAFT_URL: &str = "https://datatracker.ietf.org/doc/draft-ietf-keytrans-protocol/";
const KATIE_URL: &str = "https://github.com/Bren2010/katie";
const VERIFICATION_URL: &str = "https://github.com/felixlinker/keytrans-verification";

/// Renders the report as a complete HTML document.
#[must_use]
pub fn render(report: &Report) -> String {
    let mut out = String::with_capacity(256 * 1024);
    let _ = write!(out, "{}", head(report));
    let _ = write!(out, "{}", summary(report));
    let _ = write!(out, "{}", provenance(report));
    for suite in &report.suites {
        let _ = write!(out, "{}", suite_section(suite));
    }
    let _ = write!(out, "{}", coverage_section(report));
    let _ = write!(out, "{}", reuse_section(report));
    let _ = write!(out, "{}", footer(report));
    out
}

fn head(report: &Report) -> String {
    format!(
        r##"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>kt — IETF Key Transparency interop evidence</title>
<meta name="description" content="Differential test results for a Rust implementation of {draft} against the Go implementations.">
<style>{css}</style>
</head>
<body>
<header>
<h1>IETF Key Transparency interop evidence</h1>
<p class="lede">
  <a href="{repo}">kt</a> is a Rust implementation of
  <a href="{draft_url}">{draft}</a>, built to produce and consume the same bytes as
  the Go implementations. This page is generated by the same code that runs in CI:
  every row below is a comparison against a value produced by
  <a href="{katie}">katie</a>, and it is regenerated on every push to
  <code>main</code>.
</p>
<p class="lede">
  <strong>What &ldquo;verified&rdquo; means here.</strong> A committed test vector
  records what the Go peer computed, at a named commit, and this implementation
  recomputes it from the draft and compares byte for byte. It does not mean the
  two implementations have talked to each other over a wire — that is the next
  tier of work, and the <a href="#coverage">coverage table</a> says so plainly.
  Areas with no vector are listed there as unverified rather than omitted.
</p>
</header>
"##,
        draft = escape(&report.draft),
        draft_url = DRAFT_URL,
        repo = REPO,
        katie = KATIE_URL,
        css = CSS,
    )
}

fn summary(report: &Report) -> String {
    let failed = report.failed();
    let (class, verdict) = if failed == 0 {
        ("pass", "all checks agree".to_owned())
    } else {
        ("fail", format!("{failed} checks disagree"))
    };

    let mut rows = String::new();
    for suite in &report.suites {
        let _ = write!(
            rows,
            r##"<tr>
<td><a href="#{anchor}">{title}</a></td>
<td class="num">{cases}</td>
<td class="num">{checks}</td>
<td>{badge}</td>
</tr>
"##,
            anchor = anchor(&suite.primitive),
            title = escape(&suite.title),
            cases = suite.cases.len(),
            checks = suite.checks(),
            badge = badge(Verdict::of(suite.passing())),
        );
    }

    format!(
        r##"<section>
<div class="verdict {class}">
  <span class="verdict-label">{verdict}</span>
  <span class="verdict-detail">{checks} checks across {cases} cases in {suites} vector files</span>
</div>
<table>
<thead><tr><th>Primitive</th><th class="num">Cases</th><th class="num">Checks</th><th>Result</th></tr></thead>
<tbody>
{rows}</tbody>
</table>
</section>
"##,
        checks = report.checks(),
        cases = report.cases(),
        suites = report.suites.len(),
    )
}

fn provenance(report: &Report) -> String {
    let p = &report.provenance;
    let mut rows = String::new();
    let mut row = |label: &str, value: String| {
        let _ = writeln!(rows, "<tr><th>{}</th><td>{value}</td></tr>", escape(label));
    };

    row("Generated", escape(&p.generated_at));
    match (&p.commit, &p.commit_url) {
        (Some(sha), Some(url)) => row(
            "kt commit",
            format!(
                r#"<a href="{}"><code>{}</code></a>"#,
                escape(url),
                escape(short(sha))
            ),
        ),
        (Some(sha), None) => row("kt commit", format!("<code>{}</code>", escape(sha))),
        _ => row(
            "kt commit",
            "<span class=\"unknown\">not recorded (local build)</span>".to_owned(),
        ),
    }
    if let Some(url) = &p.run_url {
        row("CI run", format!(r#"<a href="{0}">{0}</a>"#, escape(url)));
    }
    if let Some(rustc) = &p.rustc {
        row("Rust toolchain", format!("<code>{}</code>", escape(rustc)));
    }
    if let Some(go) = &p.go {
        row("Go toolchain", format!("<code>{}</code>", escape(go)));
    }
    for suite in &report.suites {
        row(
            &format!("{} oracle", suite.title),
            format!(
                r#"<a href="{katie}/tree/{sha}">{impl_} @ <code>{short}</code></a>"#,
                katie = KATIE_URL,
                sha = escape(&suite.generator.sha),
                impl_ = escape(&suite.generator.implementation),
                short = escape(short(&suite.generator.sha)),
            ),
        );
    }

    format!(
        r#"<section id="provenance">
<h2>Provenance</h2>
<p>
  Everything needed to reproduce this page or to blame a failure: which commit of
  this implementation was tested, and which commit of the peer produced the
  expected values. A vector without its generator's commit cannot be regenerated,
  which makes it worthless the day it fails.
</p>
<table class="kv">
<tbody>
{rows}</tbody>
</table>
<h3>Reproduce it</h3>
<pre><code>git clone --recurse-submodules {repo}.git
cd kt

# regenerate the vectors from the pinned Go peer — this must produce no diff
cd interop/go &amp;&amp; go run ./cmd/gen -out ../vectors &amp;&amp; cd ../..
git diff --exit-code -- interop/vectors

# check them from the Rust side, and rebuild this page
cargo test --workspace
cargo run -p kt-interop --bin kt-interop-report -- --vectors interop/vectors --out site</code></pre>
</section>
"#,
        repo = REPO,
    )
}

fn suite_section(suite: &Suite) -> String {
    let mut rows = String::new();
    for case in &suite.cases {
        let _ = write!(rows, "{}", case_row(case));
    }

    let suite_note = if suite.negative_cases() > 0 {
        format!(
            "{} of these cases assert a <em>refusal</em>: the peer says the input must be rejected, \
             and accepting it would be the failure.",
            suite.negative_cases()
        )
    } else {
        String::new()
    };

    format!(
        r##"<section id="{anchor}">
<h2>{title} <span class="section-ref">{section}</span></h2>
<p class="meta">
  Vectors: <a href="{repo}/blob/main/interop/vectors/{file}"><code>{file}</code></a>
  · oracle: <code>{impl_} @ {short}</code>{suite_extra}
  · {cases} cases, {checks} checks {badge}
</p>
<p>{suite_note}</p>
<table class="cases">
<thead><tr><th>Case</th><th>Input</th><th>Checks</th><th>Result</th></tr></thead>
<tbody>
{rows}</tbody>
</table>
</section>
"##,
        anchor = anchor(&suite.primitive),
        title = escape(&suite.title),
        section = escape(&suite.draft_section),
        repo = REPO,
        file = escape(&suite.file),
        impl_ = escape(&suite.generator.implementation),
        short = escape(short(&suite.generator.sha)),
        suite_extra = suite
            .cipher_suite
            .as_ref()
            .map_or_else(String::new, |cs| format!(
                " · cipher suite <code>{}</code>",
                escape(cs)
            )),
        cases = suite.cases.len(),
        checks = suite.checks(),
        badge = badge(Verdict::of(suite.passing())),
    )
}

fn case_row(case: &Case) -> String {
    let mut checks = String::new();
    for check in &case.checks {
        let _ = write!(checks, "{}", check_block(check));
    }

    format!(
        r#"<tr class="case {class}">
<td><code>{name}</code>{negative}</td>
<td class="input">{input}</td>
<td><details><summary>{count} checks</summary>{checks}</details></td>
<td>{badge}</td>
</tr>
"#,
        class = if case.verdict().failed() {
            "failed"
        } else {
            "passed"
        },
        name = escape(&case.name),
        negative = if case.negative {
            r#" <span class="tag">must refuse</span>"#
        } else {
            ""
        },
        input = escape(&case.input),
        count = case.checks.len(),
        badge = badge(case.verdict()),
    )
}

fn check_block(check: &Check) -> String {
    let nested = if check.children.is_empty() {
        String::new()
    } else {
        let failures: Vec<&Check> = check
            .children
            .iter()
            .filter(|c| c.verdict.failed())
            .collect();
        if failures.is_empty() {
            format!(
                r#"<p class="nested">{} sub-checks, every one an agreement. Each is listed \
individually in <a href="report.json">report.json</a>.</p>"#,
                check.children.len()
            )
        } else {
            let mut list = String::from(r#"<ul class="nested-failures">"#);
            for failure in failures {
                let _ = write!(
                    list,
                    "<li><code>{}</code>: expected <code>{}</code>, got <code>{}</code></li>",
                    escape(&failure.what),
                    escape(&failure.expected),
                    escape(&failure.got),
                );
            }
            list.push_str("</ul>");
            list
        }
    };

    format!(
        r#"<div class="check {class}">
<div class="check-what">{badge} {what}</div>
<div class="values"><span class="label">peer</span><code class="value">{expected}</code></div>
<div class="values"><span class="label">kt</span><code class="value">{got}</code></div>
{nested}</div>
"#,
        class = if check.verdict.failed() {
            "failed"
        } else {
            "passed"
        },
        badge = badge(check.verdict),
        what = escape(&check.what),
        expected = escape(&check.expected),
        got = escape(&check.got),
    )
}

fn coverage_section(report: &Report) -> String {
    let mut rows = String::new();
    for area in &report.coverage {
        let _ = write!(rows, "{}", coverage_row(area));
    }

    let verified = report.areas_with(Coverage::VerifiedAgainstPeer).count();
    let unverified = report.areas_with(Coverage::ImplementedUnverified).count();
    let missing = report.areas_with(Coverage::NotImplemented).count();
    let out_of_scope = report.areas_with(Coverage::OutOfScope).count();
    let refuses = report
        .coverage
        .iter()
        .filter(|area| area.has_refusal_evidence())
        .count();

    format!(
        r##"<section id="coverage">
<h2>Coverage</h2>
<p>
  {verified} areas of the protocol are verified against the peer, {unverified} are
  implemented without a peer confirming the bytes, {missing} are not implemented,
  and {out_of_scope} are deliberately excluded. The unimplemented rows are listed on
  purpose: a page that showed only the passing ones would be a claim about this
  implementation's completeness that is not true.
</p>
<p>
  The <strong>Refuses</strong> column is the one to read second. &ldquo;Values
  only&rdquo; means the peer and this implementation agree on what to <em>compute</em>
  — which a verifier that accepted everything would also satisfy, because nothing in
  that file asks it to say no. {refuses} areas additionally have vectors in
  <a href="#tampered"><code>tampered.json</code></a>, where the peer has confirmed a
  proof is invalid and this implementation has to reject it too. Areas with no verifier
  to speak of — the tree arithmetic in §4.1 and §5 — have nothing to refuse.
</p>
<table class="coverage">
<thead><tr><th>Draft</th><th>Area</th><th>Module</th><th>State</th><th>Evidence</th><th>Refuses</th></tr></thead>
<tbody>
{rows}</tbody>
</table>
</section>
"##
    )
}

fn coverage_row(area: &Area) -> String {
    let class = match area.coverage {
        Coverage::VerifiedAgainstPeer => "verified",
        Coverage::ImplementedUnverified => "partial",
        Coverage::NotImplemented | Coverage::OutOfScope => "missing",
    };
    format!(
        r##"<tr class="{class}">
<td class="section-ref">{section}</td>
<td>{name}</td>
<td>{module}</td>
<td><span class="state {class}">{state}</span></td>
<td>{evidence}</td>
<td>{refuses}</td>
</tr>
"##,
        section = escape(&area.section),
        name = escape(&area.name),
        module = area.module.as_ref().map_or_else(
            || "&mdash;".to_owned(),
            |m| format!("<code>{}</code>", escape(m))
        ),
        state = escape(area.coverage.label()),
        evidence = if area.evidence.is_empty() {
            "&mdash;".to_owned()
        } else {
            area.evidence
                .iter()
                .map(|file| {
                    format!(
                        r##"<a href="#{anchor}"><code>{file}</code></a>"##,
                        anchor = anchor(file.trim_end_matches(".json")),
                        file = escape(file)
                    )
                })
                .collect::<Vec<_>>()
                .join("<br>")
        },
        refuses = if area.has_refusal_evidence() {
            r#"<span class="badge pass">yes</span>"#
        } else if matches!(area.coverage, Coverage::VerifiedAgainstPeer) {
            r#"<span class="tag">values only</span>"#
        } else {
            "&mdash;"
        },
    )
}

fn reuse_section(report: &Report) -> String {
    let mut files = String::new();
    for suite in &report.suites {
        let _ = write!(
            files,
            r#"<li><a href="{repo}/blob/main/interop/vectors/{file}"><code>{file}</code></a> — {title}, {section}</li>"#,
            repo = REPO,
            file = escape(&suite.file),
            title = escape(&suite.title),
            section = escape(&suite.draft_section),
        );
    }

    format!(
        r#"<section id="reuse">
<h2>Use these vectors</h2>
<p>
  The vectors are data, not code, and are meant to be reused by any
  implementation of the draft. They carry no licence obligation from the AGPL-3.0
  generator that produced them; the generator is a separate Go module for exactly
  that reason.
</p>
<ul>{files}</ul>
<p>The format is one JSON file per primitive. The rules that matter when consuming them:</p>
<ul>
  <li>All byte strings are lowercase hex, no <code>0x</code> prefix.</li>
  <li><code>cipher_suite</code> is the IANA <code>CipherSuite</code> value, and is
      absent for primitives that do not depend on one.</li>
  <li><code>generator.sha</code> is the commit of the implementation that produced
      the expected values.</li>
  <li><code>name</code> is stable and unique within a file; it is the test identifier.</li>
  <li>Negative cases carry <code>"expect": {{"error": true}}</code> — never an error
      string, since error text is implementation-specific.</li>
  <li>In a table of sub-results, an expected <code>null</code> means <em>must
      refuse</em>: the input has no answer, and producing one is a failure.</li>
</ul>
<p>
  <strong>Both directions.</strong> Everything on this page is Go &rarr; Rust: the
  peer computed a value and this implementation recomputed it. The other direction
  runs in CI rather than here, because the peer is the one deciding and its verdict
  is not ours to render: <code>kt-interop-emit</code> writes proofs built by this
  implementation, half of them deliberately corrupted, and
  <a href="{repo}/blob/main/interop/go/cmd/verify/main.go"><code>interop/go/cmd/verify</code></a>
  runs each one through katie&rsquo;s own verifiers &mdash; every honest proof must
  be accepted and evaluate to the root we claim, every corrupted one must be
  rejected. That is the direction that catches <em>over-acceptance</em>, where a
  client believes a proof the peer would refuse, and comparing recomputed values
  cannot see it. The fixtures are
  <a href="{repo}/blob/main/interop/vectors/from-kt.json"><code>from-kt.json</code></a>.
</p>
<p>
  This page's own results are also available as
  <a href="report.json"><code>report.json</code></a>, with every sub-check
  included, in case you would rather diff than read.
</p>
<p>
  If your implementation disagrees with a vector, that is worth reporting — it is
  either a bug here, a bug in the peer, or an ambiguity in the draft, and the
  third is the most valuable of the three. Issues go to
  <a href="{repo}/issues">{repo}/issues</a>. The second Go implementation,
  <a href="{verification}">keytrans-verification</a>, is Gobra-verified and is a
  useful third opinion when two implementations disagree.
</p>
</section>
"#,
        repo = REPO,
        verification = VERIFICATION_URL,
    )
}

fn footer(report: &Report) -> String {
    format!(
        r#"<footer>
<p>
  Generated by <code>kt-interop-report</code> from
  <a href="{repo}">{repo}</a>. The generator, the vectors, and the tests that
  enforce them are all in that repository; this page is a rendering of
  <code>cargo test</code>, not a summary written by hand.
</p>
<p>
  kt is implemented from the draft text. The Go implementations are interop peers,
  run and compared against, never copied — <a href="{repo}/blob/main/docs/licensing.md">licensing.md</a>
  explains why that boundary is a rule rather than a preference.
</p>
<p class="stamp">{generated} · {checks} checks · draft {draft}</p>
</footer>
</body>
</html>
"#,
        repo = REPO,
        generated = escape(&report.provenance.generated_at),
        checks = report.checks(),
        draft = escape(&report.draft),
    )
}

fn badge(verdict: Verdict) -> String {
    match verdict {
        Verdict::Pass => r#"<span class="badge pass">agrees</span>"#.to_owned(),
        Verdict::Fail => r#"<span class="badge fail">disagrees</span>"#.to_owned(),
    }
}

/// A stable, readable anchor from a primitive or file name.
fn anchor(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect()
}

/// The first 12 characters of a git object id, or the whole thing if shorter.
fn short(sha: &str) -> &str {
    sha.get(..12).unwrap_or(sha)
}

/// Escapes text for HTML. Applied to every value that comes from a vector file,
/// which is to say to everything on the page that is not a literal.
fn escape(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

const CSS: &str = r#"
:root {
  color-scheme: light dark;
  --bg: #fbfbfa; --fg: #1a1a19; --muted: #5f5f5b; --line: #e2e2dd;
  --card: #ffffff; --code-bg: #f4f4f1;
  --pass: #17703f; --pass-bg: #e8f5ec; --fail: #a32020; --fail-bg: #fdeceb;
  --partial: #8a5a00; --partial-bg: #fdf3e0; --link: #1f5fa8;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #16171a; --fg: #e8e8e4; --muted: #a0a09a; --line: #2c2e33;
    --card: #1c1e22; --code-bg: #232529;
    --pass: #6cc48d; --pass-bg: #16281d; --fail: #f08a83; --fail-bg: #2b1a19;
    --partial: #d8a94f; --partial-bg: #2a2314; --link: #7fb3f0;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0 auto; padding: 2.5rem 1.25rem 4rem; max-width: 62rem;
  background: var(--bg); color: var(--fg);
  font: 16px/1.6 ui-sans-serif, -apple-system, "Segoe UI", Roboto, sans-serif;
}
h1 { font-size: 1.75rem; line-height: 1.25; margin: 0 0 1rem; letter-spacing: -0.01em; }
h2 { font-size: 1.25rem; margin: 2.5rem 0 0.5rem; letter-spacing: -0.01em; }
h3 { font-size: 1rem; margin: 1.5rem 0 0.5rem; }
p { margin: 0 0 1rem; }
a { color: var(--link); }
code { font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace; font-size: 0.875em; }
pre {
  background: var(--code-bg); border: 1px solid var(--line); border-radius: 6px;
  padding: 0.875rem 1rem; overflow-x: auto; font-size: 0.8125rem; line-height: 1.5;
}
pre code { font-size: inherit; }
.lede { color: var(--muted); max-width: 46rem; }
.lede strong { color: var(--fg); }
header { border-bottom: 1px solid var(--line); padding-bottom: 1.5rem; }
section { margin-top: 1rem; }
.meta { color: var(--muted); font-size: 0.875rem; }
.section-ref { color: var(--muted); font-weight: 400; font-size: 0.8125rem; white-space: nowrap; }
.verdict {
  display: flex; flex-wrap: wrap; gap: 0.5rem 1rem; align-items: baseline;
  margin: 1.5rem 0; padding: 1rem 1.25rem; border-radius: 8px;
  border: 1px solid var(--line);
}
.verdict.pass { background: var(--pass-bg); border-color: color-mix(in oklab, var(--pass) 35%, transparent); }
.verdict.fail { background: var(--fail-bg); border-color: color-mix(in oklab, var(--fail) 35%, transparent); }
.verdict-label { font-size: 1.125rem; font-weight: 600; }
.verdict.pass .verdict-label { color: var(--pass); }
.verdict.fail .verdict-label { color: var(--fail); }
.verdict-detail { color: var(--muted); font-size: 0.875rem; }
table { width: 100%; border-collapse: collapse; margin: 0.5rem 0 1rem; font-size: 0.9375rem; display: block; overflow-x: auto; }
thead { text-align: left; }
th, td { padding: 0.5rem 0.75rem; border-bottom: 1px solid var(--line); vertical-align: top; }
th { font-size: 0.8125rem; text-transform: uppercase; letter-spacing: 0.04em; color: var(--muted); font-weight: 600; }
td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
/* File and module names are long single tokens, and breaking them mid-word to
   fit a narrow column is harder to read than scrolling. Tables already scroll
   (display: block; overflow-x: auto), so give them a floor and let them. */
table.coverage { font-size: 0.875rem; min-width: 42rem; }
table.cases { min-width: 38rem; }
table.kv th { text-transform: none; letter-spacing: 0; font-size: 0.9375rem; color: var(--muted); white-space: nowrap; width: 14rem; }
.badge {
  display: inline-block; padding: 0.0625rem 0.5rem; border-radius: 999px;
  font-size: 0.75rem; font-weight: 600; white-space: nowrap;
}
.badge.pass { background: var(--pass-bg); color: var(--pass); }
.badge.fail { background: var(--fail-bg); color: var(--fail); }
.tag {
  display: inline-block; padding: 0.0625rem 0.375rem; border-radius: 4px;
  background: var(--code-bg); color: var(--muted); font-size: 0.6875rem;
  text-transform: uppercase; letter-spacing: 0.04em; white-space: nowrap;
}
td.input { color: var(--muted); font-size: 0.875rem; }
summary { cursor: pointer; color: var(--link); font-size: 0.875rem; }
.check { margin: 0.75rem 0 0; padding: 0.625rem 0.75rem; border-left: 2px solid var(--line); background: var(--card); }
.check.failed { border-left-color: var(--fail); }
.check-what { font-size: 0.875rem; font-weight: 600; margin-bottom: 0.375rem; }
.values { display: flex; gap: 0.5rem; align-items: baseline; margin-top: 0.125rem; }
.values .label { color: var(--muted); font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.04em; min-width: 2.5rem; }
.value {
  background: var(--code-bg); padding: 0.125rem 0.375rem; border-radius: 4px;
  overflow-wrap: anywhere; max-height: 9rem; overflow-y: auto; display: block; flex: 1;
}
.check.failed .values:last-of-type .value { background: var(--fail-bg); color: var(--fail); }
.nested { color: var(--muted); font-size: 0.8125rem; margin: 0.5rem 0 0; }
.nested-failures { margin: 0.5rem 0 0; padding-left: 1.25rem; font-size: 0.8125rem; }
.state { display: inline-block; padding: 0.0625rem 0.5rem; border-radius: 999px; font-size: 0.75rem; font-weight: 600; white-space: nowrap; }
.state.verified { background: var(--pass-bg); color: var(--pass); }
.state.partial { background: var(--partial-bg); color: var(--partial); }
.state.missing { background: var(--code-bg); color: var(--muted); }
tr.missing td:not(.section-ref) { color: var(--muted); }
.unknown { color: var(--muted); }
footer { margin-top: 3rem; padding-top: 1.5rem; border-top: 1px solid var(--line); color: var(--muted); font-size: 0.875rem; }
.stamp { font-size: 0.8125rem; }
@media (max-width: 40rem) {
  body { padding: 1.5rem 1rem 3rem; }
  table.kv th { width: auto; }
}
"#;
