[package]
name = "kt-wire"
description = "TLS presentation language codec and protocol structs for IETF Key Transparency"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]


[lints]
workspace = true
