//! Differential tests against `interop/vectors/ibst.json` and
//! `interop/vectors/binary-ladder.json` (`docs/interop.md` Tier 1, step 6).
//!
//! Both files are generated by `interop/go/cmd/gen` from the pinned `katie`
//! submodule. These are the cheapest interop assertions available — pure integer
//! math, no hashing, no keys, no state — and everything above them is defined in
//! terms of the node indices and versions they produce, so a disagreement here
//! would otherwise show up as an unexplained proof failure much later.
//!
//! The vectors also pin the *refusals*: where a vector says `null`, the input has
//! no answer (a leaf's child, the rightmost entry's right child) and this
//! implementation must return an error rather than a plausible-looking index.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    reason = "a test that cannot fail loudly is not a test"
)]

use std::fs;
use std::path::PathBuf;

use kt_tree::{ibst, ladder};
use serde::Deserialize;
use serde::de::DeserializeOwned;

/// The vector file format from `interop/README.md`, generic over the shape of a
/// case so the two files can share it.
///
/// `cipher_suite` is absent from both of these files: the implicit binary search
/// tree and the binary ladders do not depend on a suite.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct VectorFile<I, E> {
    primitive: String,
    draft: String,
    generator: Generator,
    #[serde(default)]
    #[allow(dead_code, reason = "part of the file contract; not asserted on")]
    notes: String,
    cases: Vec<Case<I, E>>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Generator {
    #[serde(rename = "impl")]
    implementation: String,
    sha: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Case<I, E> {
    name: String,
    input: I,
    expect: E,
}

fn load<I: DeserializeOwned, E: DeserializeOwned>(name: &str) -> VectorFile<I, E> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../interop/vectors")
        .join(name);
    let raw =
        fs::read_to_string(&path).unwrap_or_else(|err| panic!("reading {}: {err}", path.display()));
    serde_json::from_str(&raw).unwrap_or_else(|err| panic!("parsing {}: {err}", path.display()))
}

/// Shared provenance checks: a vector that cannot be regenerated is worthless the
/// day it fails, and case names are the test identifiers.
fn check_provenance<I, E>(file: &VectorFile<I, E>, primitive: &str, section: &str) {
    assert_eq!(file.primitive, primitive);
    assert!(
        file.draft.starts_with(kt_wire::DRAFT),
        "vectors target {:?} but this workspace implements {:?}",
        file.draft,
        kt_wire::DRAFT
    );
    assert!(
        file.draft.contains(section),
        "{:?} should cite {section}",
        file.draft
    );
    assert_eq!(file.generator.implementation, "katie");
    assert_eq!(
        file.generator.sha.len(),
        40,
        "generator SHA must be a full git object id"
    );
    assert!(file.generator.sha.chars().all(|c| c.is_ascii_hexdigit()));
    assert!(!file.cases.is_empty(), "no cases");

    let mut names: Vec<&str> = file.cases.iter().map(|c| c.name.as_str()).collect();
    names.sort_unstable();
    let count = names.len();
    names.dedup();
    assert_eq!(names.len(), count, "case names must be unique");
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct IbstInput {
    size: u64,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct IbstExpect {
    root: u64,
    frontier: Vec<u64>,
    nodes: Vec<NodeExpect>,
}

/// One node's children. `None` means the peer has no answer either: `left` is
/// null for a leaf, `right` is null for the rightmost entry of the log.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct NodeExpect {
    index: u64,
    left: Option<u64>,
    right: Option<u64>,
}

#[test]
fn ibst_vectors_match() {
    let file: VectorFile<IbstInput, IbstExpect> = load("ibst.json");
    check_provenance(&file, "ibst", "§4.1");

    let mut null_lefts = 0_usize;
    let mut null_rights = 0_usize;

    for case in &file.cases {
        let size = case.input.size;

        assert_eq!(
            ibst::root(size),
            Ok(case.expect.root),
            "case {}: root",
            case.name
        );
        assert_eq!(
            ibst::frontier(size).as_deref(),
            Ok(case.expect.frontier.as_slice()),
            "case {}: frontier",
            case.name
        );

        for node in &case.expect.nodes {
            let index = node.index;
            match node.left {
                Some(expected) => {
                    assert_eq!(
                        ibst::left(index),
                        Ok(expected),
                        "case {}: left({index})",
                        case.name
                    );
                }
                None => {
                    null_lefts = null_lefts.saturating_add(1);
                    assert_eq!(
                        ibst::left(index),
                        Err(ibst::Error::LeafHasNoChildren { index }),
                        "case {}: left({index}) must be refused",
                        case.name
                    );
                }
            }
            match node.right {
                Some(expected) => {
                    assert_eq!(
                        ibst::right(index, size),
                        Ok(expected),
                        "case {}: right({index}, {size})",
                        case.name
                    );
                }
                None => {
                    null_rights = null_rights.saturating_add(1);
                    // Either because it is a leaf, or because it is the rightmost
                    // entry and its right subtree is empty. Both are refusals, and
                    // which one it is depends on the index, not on the caller.
                    let expected = if ibst::is_leaf(index) {
                        ibst::Error::LeafHasNoChildren { index }
                    } else {
                        ibst::Error::NoRightChild { index, size }
                    };
                    assert_eq!(
                        ibst::right(index, size),
                        Err(expected),
                        "case {}: right({index}, {size}) must be refused",
                        case.name
                    );
                }
            }
        }
    }

    // If a regeneration ever drops the refusal cases, the file would still pass
    // every assertion above while testing strictly less.
    assert!(null_lefts > 0, "no leaf-has-no-child cases in the vectors");
    assert!(
        null_rights > 0,
        "no empty-right-subtree cases in the vectors"
    );
}

/// The three ladder variants from Appendix B, tagged by `kind` in the vector.
#[derive(Debug, Deserialize)]
#[serde(tag = "kind", rename_all = "lowercase", deny_unknown_fields)]
enum LadderInput {
    /// The full ladder that pins a greatest version (§5).
    Base { greatest: u32 },
    /// A search ladder for a target version (§6.2).
    Search {
        target: u32,
        greatest: u32,
        left_inclusion: Vec<u32>,
        right_non_inclusion: Vec<u32>,
    },
    /// A monitoring ladder for a monitored version (§8.1).
    Monitoring {
        target: u32,
        left_inclusion: Vec<u32>,
    },
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct LadderExpect {
    versions: Vec<u32>,
}

#[test]
fn binary_ladder_vectors_match() {
    let file: VectorFile<LadderInput, LadderExpect> = load("binary-ladder.json");
    check_provenance(&file, "binary-ladder", "§5");

    let mut kinds = [0_usize; 3];
    for case in &file.cases {
        let expected = case.expect.versions.as_slice();
        match &case.input {
            LadderInput::Base { greatest } => {
                kinds[0] = kinds[0].saturating_add(1);
                assert_eq!(
                    ladder::base_binary_ladder(*greatest).as_deref(),
                    Ok(expected),
                    "case {}: base ladder for greatest {greatest}",
                    case.name
                );
            }
            LadderInput::Search {
                target,
                greatest,
                left_inclusion,
                right_non_inclusion,
            } => {
                kinds[1] = kinds[1].saturating_add(1);
                assert_eq!(
                    ladder::search_binary_ladder(
                        *target,
                        *greatest,
                        left_inclusion,
                        right_non_inclusion
                    )
                    .as_deref(),
                    Ok(expected),
                    "case {}: search ladder for target {target}, greatest {greatest}",
                    case.name
                );
            }
            LadderInput::Monitoring {
                target,
                left_inclusion,
            } => {
                kinds[2] = kinds[2].saturating_add(1);
                assert_eq!(
                    ladder::monitoring_binary_ladder(*target, left_inclusion),
                    expected,
                    "case {}: monitoring ladder for target {target}",
                    case.name
                );
            }
        }
    }

    // All three variants must be covered; a file of nothing but base ladders
    // would pass while leaving the truncation and deduplication rules untested.
    assert!(kinds[0] > 0, "no base ladder cases");
    assert!(kinds[1] > 0, "no search ladder cases");
    assert!(kinds[2] > 0, "no monitoring ladder cases");

    // The deduplication rules are the part most likely to be implemented
    // plausibly-but-wrongly, so require that the vectors exercise them.
    let with_dedup = file
        .cases
        .iter()
        .filter(|c| match &c.input {
            LadderInput::Search {
                left_inclusion,
                right_non_inclusion,
                ..
            } => !left_inclusion.is_empty() || !right_non_inclusion.is_empty(),
            _ => false,
        })
        .count();
    assert!(
        with_dedup > 0,
        "no search ladder cases with an already-proven lookup"
    );
}
