//! Differential test against `interop/vectors/commitment.json`
//! (`docs/interop.md` Tier 1, step 1).
//!
//! The vectors are generated by `interop/go/cmd/gen` from the pinned `katie`
//! submodule and committed as data. This test recomputes both the
//! `CommitmentValue` encoding (§2.1, §11.6) and the commitment
//! `HMAC(Kc, CommitmentValue)` (§11.6) from the draft and asserts byte equality,
//! so a disagreement with the Go peer fails here rather than three layers up.
//!
//! Two things are asserted separately on purpose: the serialized
//! `CommitmentValue` and the HMAC over it. A wire-encoding bug and an HMAC bug
//! produce the same symptom at the top level and want different fixes.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    reason = "a test that cannot fail loudly is not a test"
)]

use std::fs;
use std::path::PathBuf;

use kt_crypto::commitment::{self, Commitment};
use kt_crypto::suite::CipherSuite;
use kt_wire::structs::{CommitmentValue, DeploymentMode, UpdateSuffix, UpdateValue};
use serde::Deserialize;

/// The vector file format from `interop/README.md`.
///
/// `deny_unknown_fields` throughout: if the generator starts emitting a field
/// this test does not know about, that is drift in the contract and should fail
/// loudly rather than be skipped silently.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct VectorFile {
    primitive: String,
    draft: String,
    generator: Generator,
    cipher_suite: u16,
    #[serde(default)]
    #[allow(dead_code, reason = "part of the file contract; not asserted on")]
    notes: String,
    cases: Vec<Case>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Generator {
    #[serde(rename = "impl")]
    implementation: String,
    sha: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Case {
    name: String,
    input: Input,
    expect: Expect,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Input {
    opening: String,
    label: String,
    version: u32,
    update: Update,
    /// Present on negative cases: the commitment that must *not* verify.
    #[serde(default)]
    commitment: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Update {
    value: String,
    /// Only under `thirdPartyManagement` (§11.5).
    #[serde(default)]
    signature: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Expect {
    #[serde(default)]
    commitment: Option<String>,
    #[serde(default)]
    commitment_value: Option<String>,
    #[serde(default)]
    error: bool,
}

fn vector_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../interop/vectors/commitment.json")
}

fn load() -> VectorFile {
    let path = vector_path();
    let raw =
        fs::read_to_string(&path).unwrap_or_else(|err| panic!("reading {}: {err}", path.display()));
    serde_json::from_str(&raw).unwrap_or_else(|err| panic!("parsing {}: {err}", path.display()))
}

fn unhex(hex: &str, what: &str) -> Vec<u8> {
    hex::decode(hex).unwrap_or_else(|err| panic!("{what} is not valid hex: {err}"))
}

impl Input {
    /// The `CommitmentValue` this case describes, and the mode it implies.
    fn commitment_value(&self) -> (CommitmentValue, DeploymentMode) {
        let (suffix, mode) = match &self.update.signature {
            None => (UpdateSuffix::Empty, DeploymentMode::ContactMonitoring),
            Some(sig) => (
                UpdateSuffix::ThirdPartyManagement {
                    signature: unhex(sig, "update.signature"),
                },
                DeploymentMode::ThirdPartyManagement,
            ),
        };
        let value = CommitmentValue {
            opening: unhex(&self.opening, "opening"),
            label: unhex(&self.label, "label"),
            version: self.version,
            update: UpdateValue {
                value: unhex(&self.update.value, "update.value"),
                suffix,
            },
        };
        (value, mode)
    }
}

/// The file's own provenance fields, per the contract in `interop/README.md`.
/// A vector whose generator SHA is missing cannot be regenerated, which makes it
/// useless the day it fails.
#[test]
fn vector_file_is_well_formed() {
    let file = load();
    assert_eq!(file.primitive, "commitment");
    assert!(
        file.draft.starts_with(kt_wire::DRAFT),
        "vectors target {:?} but this workspace implements {:?}",
        file.draft,
        kt_wire::DRAFT
    );
    assert_eq!(file.generator.implementation, "katie");
    assert_eq!(
        file.generator.sha.len(),
        40,
        "generator SHA must be a full git object id"
    );
    assert!(file.generator.sha.chars().all(|c| c.is_ascii_hexdigit()));
    assert!(CipherSuite::from_code(file.cipher_suite).is_ok());

    let (positive, negative): (Vec<_>, Vec<_>) = file.cases.iter().partition(|c| !c.expect.error);
    assert!(!positive.is_empty(), "no positive cases");
    assert!(
        !negative.is_empty(),
        "no negative cases: a vector file that only exercises the happy path cannot \
         catch an implementation that accepts everything"
    );

    let mut names: Vec<&str> = file.cases.iter().map(|c| c.name.as_str()).collect();
    names.sort_unstable();
    let count = names.len();
    names.dedup();
    assert_eq!(
        names.len(),
        count,
        "case names must be unique: they are the test identifiers"
    );
}

/// The core assertion: for every positive case, the serialized
/// `CommitmentValue` and the commitment both match the Go peer byte for byte.
#[test]
fn commitment_vectors_match() {
    let file = load();
    let suite = CipherSuite::from_code(file.cipher_suite).expect("unknown cipher suite");

    let mut checked = 0_usize;
    for case in &file.cases {
        if case.expect.error {
            continue;
        }
        let (value, mode) = case.input.commitment_value();

        let encoded = commitment::encode_commitment_value(suite, &value)
            .unwrap_or_else(|err| panic!("case {}: encoding CommitmentValue: {err}", case.name));
        let expected_encoding = case.expect.commitment_value.as_deref().unwrap_or_else(|| {
            panic!("case {}: positive case without commitment_value", case.name)
        });
        assert_eq!(
            hex::encode(&encoded),
            expected_encoding,
            "case {}: CommitmentValue encoding (§2.1, §11.6)",
            case.name
        );

        // The same bytes must decode back to the same struct: the vector pins the
        // encoder, and this pins the decoder against the encoder on real bytes.
        let mut dec = kt_wire::codec::Decoder::new(&encoded);
        let decoded = CommitmentValue::decode_with_nc(&mut dec, suite.nc(), mode)
            .unwrap_or_else(|err| panic!("case {}: decoding CommitmentValue: {err}", case.name));
        dec.finish()
            .unwrap_or_else(|err| panic!("case {}: {err}", case.name));
        assert_eq!(
            decoded, value,
            "case {}: decode is not the inverse of encode",
            case.name
        );

        let got = commitment::commit(suite, &value)
            .unwrap_or_else(|err| panic!("case {}: committing: {err}", case.name));
        let expected_commitment = case
            .expect
            .commitment
            .as_deref()
            .unwrap_or_else(|| panic!("case {}: positive case without commitment", case.name));
        assert_eq!(
            hex::encode(got.as_bytes()),
            expected_commitment,
            "case {}: commitment = HMAC(Kc, CommitmentValue) (§11.6)",
            case.name
        );

        // And the verification path must agree with the computation path.
        let expected = Commitment::from_slice(&unhex(expected_commitment, "expect.commitment"))
            .unwrap_or_else(|err| panic!("case {}: {err}", case.name));
        commitment::verify(suite, &value, &expected).unwrap_or_else(|err| {
            panic!("case {}: verify rejected a valid opening: {err}", case.name)
        });

        checked = checked.checked_add(1).unwrap();
    }
    assert!(checked > 0, "no positive cases were checked");
}

/// Negative cases: inputs that the Go peer says must not verify. A verifier that
/// accepts these is broken in the direction equality-of-happy-path never shows.
#[test]
fn negative_commitment_vectors_are_rejected() {
    let file = load();
    let suite = CipherSuite::from_code(file.cipher_suite).expect("unknown cipher suite");

    let mut checked = 0_usize;
    for case in &file.cases {
        if !case.expect.error {
            continue;
        }
        let (value, _) = case.input.commitment_value();
        let raw =
            case.input.commitment.as_deref().unwrap_or_else(|| {
                panic!("case {}: negative case carries no commitment", case.name)
            });
        let commitment = Commitment::from_slice(&unhex(raw, "input.commitment"))
            .unwrap_or_else(|err| panic!("case {}: {err}", case.name));

        assert_eq!(
            commitment::verify(suite, &value, &commitment),
            Err(kt_crypto::Error::CommitmentMismatch),
            "case {}: this opening must not verify",
            case.name
        );
        // Belt and braces: recomputing must also differ, so the rejection is not
        // an artifact of the comparison path alone.
        let recomputed = commitment::commit(suite, &value)
            .unwrap_or_else(|err| panic!("case {}: committing: {err}", case.name));
        assert_ne!(recomputed, commitment, "case {}", case.name);

        checked = checked.checked_add(1).unwrap();
    }
    assert!(checked > 0, "no negative cases were checked");
}
